output:
  sort-results: true
  print-issued-lines: false

linters:
  disable-all: true
  enable:
    # golangci-lint defaults:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

    - gofumpt
    - nolintlint # lints nolint directives
    - revive

linters-settings:
  govet:
    enable:
      - niliness
      - reflectvaluecompare
      - sortslice
      - unusedwrite

  errcheck:
    exclude-functions:
      # Writing a plain string to a fmt.State cannot fail.
      - io.WriteString(fmt.State)

issues:
  # Print all issues reported by all linters.
  max-issues-per-linter: 0
  max-same-issues: 0
  # Don't ignore some of the issues that golangci-lint considers okay.
  # This includes documenting all exported entities.
  exclude-use-default: false

  exclude-rules:
    - linters: [revive]
      text: 'unused-parameter: parameter \S+ seems to be unused, consider removing or renaming it as _'
    - linters: [revive]
      text: 'empty-block: this block is empty, you can remove it'
